name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - 'refs/tags/*'
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Update to Node.js 18.x

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          NODE_OPTIONS: --openssl-legacy-provider # Add this line
        run: npm run build

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
